---
- name: Install Varnish
  apt:
    name: varnish
    state: present
    update_cache: yes
      # varnish_setup.yml

- name: Increase Varnish memory usage
  lineinfile:
    path: /etc/default/varnish
    regexp: '^DAEMON_OPTS="-a'
    line: 'DAEMON_OPTS="-a :80 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,2G"'

- name: Set Varnish service configuration
  blockinfile:
    path: /etc/systemd/system/multi-user.target.wants/varnish.service
    block: |
      [Unit]
      Description=Varnish Cache, a high-performance HTTP accelerator
      Documentation=https://www.varnish-cache.org/docs/ man:varnishd

      [Service]
      Type=simple
      LimitNOFILE=131072
      LimitMEMLOCK=85983232
      ExecStart=/usr/sbin/varnishd -j unix,user=vcache -F -a :80 -T localhost:6082 -f /etc/varnish/default.vcl -S /etc/varnish/secret -s malloc,2G
      ExecReload=/usr/share/varnish/varnishreload
      ProtectSystem=full
      ProtectHome=true
      PrivateTmp=true
      PrivateDevices=true

      [Install]
      WantedBy=multi-user.target
    create: yes
  notify:
    - Reload systemd
    - Restart varnish

- name: Configure Varnish VCL
  blockinfile:
    path: /etc/varnish/default.vcl
    block: |
      vcl 4.0;
      backend default {
          .host = "185.125.190.40";
          .port = "80";
      }
      sub vcl_recv {
          if (req.url ~ "^/14.04/ubuntu-14.04.6-desktop-i386.iso") {
              set req.backend_hint = default;
          }
      }
      sub vcl_backend_response {
          if (bereq.url ~ "^/14.04/ubuntu-14.04.6-desktop-i386.iso") {
              set beresp.ttl = 24h;
          }
      }
    marker: "# {mark} ANSIBLE MANAGED BLOCK - VARNISH BACKEND CONFIG"  # Unique marker


- name: Check Varnish configuration syntax
  command: varnishd -C -f /etc/varnish/default.vcl
  register: syntax_check
  changed_when: false
  failed_when: syntax_check.rc not in [0]


- name: Restart Varnish
  systemd:
    name: varnish
    state: restarted
