---
- name: Add Grafana GPG key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main
    state: present
    filename: 'grafana'

- name: Install Grafana
  ansible.builtin.apt:
    name: "grafana={{ grafana_version }}"
    update_cache: yes
    state: present

- name: Enable and start Grafana service
  systemd:
    name: grafana-server
    state: started
    enabled: yes

