---
- name: Basic Linux Config
  hosts: all
  become: yes
  roles:
    - common
    - exporters

- name: Basic Linux Config
  hosts: monitor
  become: yes
  roles:
    - exporters-manager

# - name: Configure Varnish servers
#   hosts: varnish
#   become: yes
#   roles:
#     - varnish_server
# 
# - name: Configure Test Clients
#   hosts: client
#   become: yes
#   roles:
#     - test_client
