---
- name: Basic Linux Config
  gather_facts: true
  hosts: all
  become: yes
  roles:
    - common
    - monitoring

# - name: Configure Varnish servers
#   hosts: varnish
#   become: yes
#   roles:
#     - varnish_server
# 
# - name: Configure Test Clients
#   hosts: client
#   become: yes
#   roles:
#     - test_client
